### PR TITLE
Added Realtime Watchdog and Parabolic Blender

### PR DESCRIPTION
**Pull request by BryceStevenWilley**
Watchdog sends halt messages when the robot is about to collide, and parabolic blender turns waypoint paths into kd-control for the robot.

### CODE REVIEW

**Comment by ndantam** [comment]
Does `pblend.h` need to be a "public" header file?  If so, please prefix all symbols with "`sns_`".  If not, please move the declarations to the source file or a "private" header.

**Comment by ndantam** [comment]
Use the `PACKAGE_VERSION` defined in `config.h`.

**Comment by ndantam** [comment]
See `aa_rx_ct_sg_limits()` defined in `amino/rx/rx_ct.h`.

**Comment by ndantam** [comment]
Use a `struct sns_motor_state_set` to receive state so that we can multiplex state messages, e.g., to control two arms.  See `sns-teleopd.c` for usage.

**Comment by ndantam** [comment]
Similarly, see `sns-teleopd.c` for multiplexed reference sending.

**Comment by ndantam** [comment]
Looks like we have a memory leak in `send_finish_and_stop()`.  You need to pop/release allocations from a memory region when finished.

**Comment by BryceStevenWilley** [comment]
Please take another look, I should have addressed all of your comments.

**Comment by BryceStevenWilley** [comment]
Actually, hold on, there are still a few issues when running on both robots.

**Comment by BryceStevenWilley** [comment]
All issues have been resolved. PTAL.

**Pull request closed without merging**
